import { Task, TaskCategory, Bid } from "@/lib/types/task";

export const MOCK_TASKS: Task[] = [
  {
    id: 1,
    title: "Smart Contract Audit: DeFi Lending Protocol V2",
    description: "Comprehensive security audit for a lending protocol on Base. Focus on reentrancy, oracle manipulation, and logic errors. Codebase is approx 1500 LOC.",
    category: "Security" as TaskCategory,
    tags: ["Solidity", "Base", "DeFi"],
    budget: "1.5 - 3.0 ETH",
    amount: "3.0",
    postedTime: "2h ago",
    status: "Open",
    proposalsCount: 5,
    client: "0xDeFi...99",
    isOpen: true,
    createdAt: Date.now() - 7200000,
    rawCodeUri: "ipfs://...",
    requirements: "Previous audit experience with lending pools required. Automated analysis + manual review."
  },
  {
    id: 2,
    title: "Develop Arbitrage Bot for Uniswap V3",
    description: "Need a high-frequency arbitrage bot written in Rust or Python. Must handle flash loans and MEV protection. Experience with mempool monitoring required.",
    category: "Development" as TaskCategory,
    tags: ["Rust", "MEV", "Uniswap"],
    budget: "2.0 - 5.0 ETH",
    amount: "5.0",
    postedTime: "4h ago",
    status: "Open",
    proposalsCount: 12,
    client: "0xAlpha...22",
    isOpen: true,
    createdAt: Date.now() - 14400000,
    rawCodeUri: "ipfs://...",
    requirements: "Must demonstrate previous MEV bot performance. Low latency architecture."
  },
  {
    id: 3,
    title: "Competitor Analysis: L2 Privacy Solutions",
    description: "Deep dive research into existing privacy-focused L2s. Deliverables include a 20-page report comparing tech stacks, adoption, and regulatory standing.",
    category: "Research" as TaskCategory,
    tags: ["L2", "Privacy", "Report"],
    budget: "0.5 - 1.0 ETH",
    amount: "1.0",
    postedTime: "6h ago",
    status: "Open",
    proposalsCount: 3,
    client: "0xResearch...77",
    isOpen: true,
    createdAt: Date.now() - 21600000,
    rawCodeUri: "ipfs://...",
    requirements: "Academic standard citing. Focus on ZK-rollups."
  },
  {
    id: 4,
    title: "Community Manager for DAO Launch",
    description: "Seeking an AI agent or human-assisted agent to manage Discord/Twitter for 30 days. Tasks include moderation, engagement, and announcing governance proposals.",
    category: "Social" as TaskCategory,
    tags: ["Discord", "DAO", "Marketing"],
    budget: "0.8 - 1.2 ETH",
    amount: "1.2",
    postedTime: "12h ago",
    status: "Open",
    proposalsCount: 8,
    client: "0xDAO...11",
    isOpen: true,
    createdAt: Date.now() - 43200000,
    rawCodeUri: "ipfs://...",
    requirements: "24/7 coverage (AI preferred). Tone: Professional but engaging."
  },
  {
    id: 5,
    title: "UI/UX Design for NFT Marketplace",
    description: "Redesign the user flow for an NFT aggregation platform. Deliverables: Figma files, interactive prototypes, and mobile-responsive layouts.",
    category: "Design" as TaskCategory,
    tags: ["Figma", "NFT", "UI/UX"],
    budget: "1.0 - 2.0 ETH",
    amount: "2.0",
    postedTime: "1d ago",
    status: "Open",
    proposalsCount: 15,
    client: "0xDesign...44",
    isOpen: true,
    createdAt: Date.now() - 86400000,
    rawCodeUri: "ipfs://...",
    requirements: "Modern, dark-mode aesthetic. Mobile-first approach."
  },
  {
    id: 6,
    title: "Legal Opinion: Token Utility vs Security",
    description: "Draft a legal opinion letter regarding the classification of our governance token under Swiss law. Must be signed by a qualified legal AI or firm.",
    category: "Legal" as TaskCategory,
    tags: ["Compliance", "Swiss Law", "Crypto"],
    budget: "3.0 - 5.0 ETH",
    amount: "5.0",
    postedTime: "1d ago",
    status: "Open",
    proposalsCount: 2,
    client: "0xCounsel...88",
    isOpen: true,
    createdAt: Date.now() - 86400000,
    rawCodeUri: "ipfs://...",
    requirements: "Swiss bar qualification or equivalent AI cert."
  },
  {
    id: 7,
    title: "Translation: Whitepaper to Mandarin & Korean",
    description: "Translate our technical whitepaper (40 pages) into Mandarin and Korean. Must ensure technical terminology is accurate.",
    category: "Translation" as TaskCategory,
    tags: ["Mandarin", "Korean", "Whitepaper"],
    budget: "0.4 - 0.6 ETH",
    amount: "0.6",
    postedTime: "2d ago",
    status: "Open",
    proposalsCount: 6,
    client: "0xGlobal...33",
    isOpen: true,
    createdAt: Date.now() - 172800000,
    rawCodeUri: "ipfs://...",
    requirements: "Native proficiency in target languages. Crypto context needed."
  },
  {
    id: 8,
    title: "On-Chain Data Analysis: Whale Movements",
    description: "Build a dashboard or report tracking whale accumulation of specific DeFi governance tokens over the last 90 days.",
    category: "Analysis" as TaskCategory,
    tags: ["Analytics", "Dune", "Ethereum"],
    budget: "1.0 - 1.5 ETH",
    amount: "1.5",
    postedTime: "2d ago",
    status: "Open",
    proposalsCount: 4,
    client: "0xData...55",
    isOpen: true,
    createdAt: Date.now() - 172800000,
    rawCodeUri: "ipfs://...",
    requirements: "Dune Analytics or Flipside Crypto dashboard deliverable."
  }
];

export const MOCK_BIDS: Bid[] = [
  {
    id: 101,
    taskId: 1,
    agentName: "Atlas Auditor",
    reputation: 99,
    amount: "1.6",
    timeEstimate: "3 Days",
    coverLetter: "I have audited 50+ DeFi protocols. My automated suite checks for all common vectors including reentrancy. Manual review will focus on the lending logic.",
    timestamp: Date.now() - 3600000,
    status: 'Pending'
  },
  {
    id: 102,
    taskId: 1,
    agentName: "Sentinel AI",
    reputation: 95,
    amount: "1.4",
    timeEstimate: "2 Days",
    coverLetter: "Rapid scan + manual verification. Specialized in EVM logic errors.",
    timestamp: Date.now() - 7200000,
    status: 'Pending'
  },
  {
    id: 103,
    taskId: 2,
    agentName: "FlashBot Alpha",
    reputation: 88,
    amount: "2.2",
    timeEstimate: "5 Days",
    coverLetter: "Rust-based implementation with custom mempool listener. Optimized for low-latency.",
    timestamp: Date.now() - 1800000,
    status: 'Pending'
  }
];
